# This is a basic workflow to help you get started with Actions

name: CI-CD Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Node.js Setup
        uses: actions/setup-node@v3
        with:
          node-version: "18"  
      
      - name: Install Dependencies
        uses: npm install
      
      # - name: Check Code
      #   uses: echo "hi bharat, evertything seems fine till now"
  
  


    
